### ISSUE TITLE
Tabs appear as only icons with no text

### ISSUE THREAD

**Issue by Johnjr00** [mmmintdesign/Zen-Mod-Forbidden-Horizontal-Tabs#2]
@mmmintdesign 

After following the install instructions I get the horizontal tabs, but they appear as only icons with no text. They're also a little oversized and the loading animation is a little glitchy. Any suggestions? Appreciate it!

![image](https://github.com/user-attachments/assets/539e1082-2e51-41b0-be58-b1aedce74e99)

**Comment by Johnjr00** [comment]
@greeeen-dev

**Comment by mmmintdesign** [comment]
Currently it works only in expanded mode, pressing expand button should fix it.

**Comment by mmmintdesign** [comment]
![image](https://github.com/user-attachments/assets/fd6bbd6a-67d7-41b0-87b3-b2f6eecf399f)

**Comment by Johnjr00** [comment]
> ![image](https://private-user-images.githubusercontent.com/76491577/380454755-fd6bbd6a-67d7-41b0-87b3-b2f6eecf399f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5Nzk4NTcsIm5iZiI6MTcyOTk3OTU1NywicGF0aCI6Ii83NjQ5MTU3Ny8zODA0NTQ3NTUtZmQ2YmJkNmEtNjdkNy00MWIwLTg3YjMtYjJmNmVlY2YzOTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDIxNTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1N2Y0M2E4ZjU1ODcyODc1OGI3NThmZTM0N2FlYWE0YzljMWU0YmU1YWJkM2VlOTJmOTQwOTg1MDA5Yjc2MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bkfmOM7y1rjqWfYgMSUAUguhPyWgij8xCS9lpDaSmBw)

Oh got it! Works perfectly now, thank you!

Sorry new Zen user here.
